[package]
name = "vertigo-forms-example-form"
version = "0.1.0"
authors = ["Michał Pokrywka <wolfmoon@o2.pl>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# vertigo = "0.6"
vertigo = { git = "https://github.com/vertigo-web/vertigo" }
vertigo-forms = { path = "../.." }
