[package]
name = "vertigo-forms-example-model-form"
version = "0.1.0"
authors = ["Michał Pokrywka <wolfmoon@o2.pl>"]
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
vertigo = "0.8"
vertigo-forms = { path = "../.." }
